version: '3'

services:
  web:
    build:
      context: ./
      dockerfile: paas/docker/web/Dockerfile
    container_name: pokerphace-domain
    ports:
      - '8080:80'
    volumes:
      - './:/app'
    networks:
      - pokerphace-network
networks:
  pokerphace-network:
      driver: bridge